[package]
name = "ernisto/replicator"
version = "0.2.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Wrapper = "ernisto/wrapper@0.4.1"
Signal = "ernisto/signal@0.1.1"